export const MIN_PASSWORD_LENGTH = 5;

export const MAX_PASSWORD_LENGTH = 64;

export const PASSWORD_REGEXP = /[a-zA-Z]/;

export enum AUTH_STATUS {
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTHORIZED = 'AUTHORIZED',
  LOADING = 'LOADING',
}
