export enum ICONS {
  DROPDOWN_CHEVRON = 'dropdownChevron',
  DROPDOWN_CURRENCY_BTC = 'dropdownCurrencyBTC',
  DROPDOWN_CURRENCY_RFUEL = 'dropdownCurrencyRFUEL',
  DROPDOWN_CURRENCY_USDT = 'dropdownCurrencyUSDT',
  MODAL_FAIL = 'modalFail',
  MODAL_SUCCESS = 'modalSuccess',
  LOGIN_METAMASK = 'loginMetamask',
  LOGIN_GOOGLE = 'loginGoogle',
  LOGIN_TWITTER = 'loginTwitter',
  LOGIN_DISCORD_INACTIVE = 'loginDiscordInactive',
  LOGIN_FACEBOOK = 'loginFacebook',
  LOGIN_REDDIT_INACTIVE = 'loginRedditInactive',
  LOGIN_MORE = 'loginMore',
  SIDEBAR_PROFILE = 'sidebarProfile',
  SIDEBAR_TRANSFER = 'sidebarTransfer',
  SIDEBAR_HISTORY = 'sidebarHistory',
  SIDEBAR_LOGOUT = 'sidebarLogout',
  UFORIKA_LOGO = 'uforikaLogo',
  FORA_COIN = 'foraCoin',
}
